# -*- coding: utf-8 -*-
"""frontEndAnvil

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wajCVWTeWuF8iTTbgA9fFXvAajq2Fqbn
"""

from ._anvil_designer import Form1Template
from anvil import *
import anvil.google.auth, anvil.google.drive
from anvil.google.drive import app_files
import plotly.graph_objects as go
import anvil.server
from anvil.media import download
from anvil.google.drive import app_files

class Form1(Form1Template):

  
  
  
  def __init__(self, **properties):
    # Set Form properties and Data Bindings.
    self.init_components(**properties)

    # Any code you write here will run when the form opens.

  def button_2_click(self, **event_args):
    """This method is called when the button is clicked"""
    #call generate stl from google colab
    anvil.server.call('downloadSTL', int(self.sizeX.text), int(self.sizeY.text), float(self.xMin.text), float(self.xMax.text), float(self.yMin.text), float(self.yMax.text), self.funct.text )
    folder = app_files.stlformachina
    f = folder.get("mesh.stl")
    download(f)
    
    pass




  def button_3_click(self, **event_args):
    """This method is called when the button is clicked"""
    media_obj = anvil.server.call('viewCloud', int(self.sizeX.text), int(self.sizeY.text), float(self.xMin.text), float(self.xMax.text), float(self.yMin.text), float(self.yMax.text), self.funct.text )
    self.image_1.source = media_obj
    self.download_link.url = media_obj
    pass